services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - IS_DOCKER=true
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_URL_LOCAL=${DATABASE_URL_LOCAL}
      - DATABASE_URL_SUPABASE=${DATABASE_URL_SUPABASE}
      - PORT=${PORT}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: